### ISSUE TITLE
Saltillo

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#23]
The `saltillo` should be consistent in size and style with the diacritic marks. It should also be differentiated from the apostrophe and a quote.

Reference font: [Andada](https://fonts.google.com/specimen/Andada+Pro)
<img width="801" alt="Screen Shot 2023-09-28 at 20 06 44" src="https://github.com/googlefonts/great-vibes/assets/48698976/f1ea1b6a-4349-4d95-830a-dd2568d25c55">

Currently in the font
<img width="673" alt="Screen Shot 2023-09-28 at 20 08 07" src="https://github.com/googlefonts/great-vibes/assets/48698976/93e98595-8bec-4efe-8d0a-d2ebd8ec4ce0">

**Comment by vv-monsalve** [comment]
Saltillos (lower and uppercase) need spacing/kerning revision

<img width="983" alt="Screen Shot 2023-10-09 at 16 39 14" src="https://github.com/googlefonts/great-vibes/assets/48698976/f13a855b-a06b-4c77-92d7-2dd7fd5ef79a">

**Comment by RobLeuschke** [comment]
I've addressed the spacing/kerning of the LC saltillo. I've also created GROUPS of each lowercase letter and linked them to their respective glyphs that use their components.
<img width="1847" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/3fd59619-7769-49b9-adfb-03347a0a0e05">

There may still be other forms that need to be addressed. I may need some directions as to what those are.

**Comment by EbenSorkin** [comment]
I adjusted the Saltillo and saltillo heights weights and stroke dynamics The capital one rises to the capital letter height and the lc one rises to the lc ascender height. The result is humorously the reverse of what is expected in a sans the the lc on not being taller because in Great Vibes the capital are the tallest.

<img width="763" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/1797f6ab-b089-40b6-a549-6519c504b8bf">

**Comment by EbenSorkin** [comment]
The weight also matches letters now and not diacritics or punctuation.

**Comment by vv-monsalve** [comment]
Than you Eben. Closing this issue here.
